name:                bellmanford
version:             0.1.0.0
github:              "githubuser/bellmanford"
license:             MIT
author:              "David Dav칩 Lavi침a"
maintainer:          "david@ddavo.me"
copyright:           "2020 David Dav칩 Lavi침a"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Bellman Ford algorithm implementation
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bellmanford#readme>

dependencies:
- base >= 4.7 && < 5
- array    # Better than lists
- fgl      # Graph
- graphviz # Loading graphs

library:
  source-dirs: src

executables:
  bellmanford-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bellmanford

tests:
  bellmanford-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bellmanford
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - test-invariant
    - QuickCheck
