stages:
  - build
  - test

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - haskell/.stack-work
    - bellman-ford-exe

build haskell:
  stage: build
  artifacts:
    paths:
      - haskell/.stack-work
      - bellman-ford-exe
  image: haskell
  script:
    - cd haskell
    - stack setup
    - stack build

test haskell:
  stage: test
  image: haskell
  script:
    - cd haskell
    - stack test
